title: Advance your python skills for data science
description: A collection of python tips and tricks that can be useful (for data scientists)
author: Balazs Kocsis

execute:
  execute_notebooks: off

sphinx:
  config:
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js

repository:
  url: https://github.com/bkocis/advance-your-python
  path_to_book:  .
  branch: master

html:
  use_issues_button: true
  use_repository_button: true
  comments:
    utterances:
      repo: "bkocis/advance-your-python"

markdown: kramdown

theme: jekyll-theme-slate