title: Advance your python skills for data science
description: A collection of python tips and tricks that can be useful (for data scientists)
author: Balazs Kocsis

execute:
  execute_notebooks: off

sphinx:
  config:
    html_js_files:
    - https://cdnjs.cloudflare.com/ajax/libs/require.js/2.3.4/require.min.js

repository:
  url: https://github.com/bkocis/advance-your-python
  path_to_book:  .
  branch: master

html:
  use_issues_button: true
  use_repository_button: true
  comments:
    utterances:
      repo: "bkocis/advance-your-python"

markdown: kramdown

theme: jekyll-theme-cayman

# Additional configuration for better design
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Site settings
email: your-email@example.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Navigation
nav_external_links:
  - title: GitHub
    url: https://github.com/bkocis/advance-your-python
  - title: Issues
    url: https://github.com/bkocis/advance-your-python/issues